# default datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql:postgres

# default jOOQ datasource
quarkus.jooq.dialect=postgresql